### ISSUE TITLE
  Sequelize [Node: 12.16.1, CLI: 2.7.0, ORM: 3.30.4]   fs.js:35  } = primordials;      ^   ReferenceError: primordials is not defined

### ISSUE THREAD

**Issue by hakanonymos** [adonespitogo/AdoBot-IO#24]
remote:        Done. Phantomjs binary available at /tmp/build_43a115e50e09530019db796929f807cd/node_modules/phantomjs-p
ebuilt/lib/phantom/bin/phantomjs
remote:
remote:        > androspy@1.0.0 postinstall /tmp/build_43a115e50e09530019db796929f807cd
remote:        > run-s migrate build
remote:
remote:
remote:        > androspy@1.0.0 migrate /tmp/build_43a115e50e09530019db796929f807cd
remote:        > sequelize db:migrate
remote:
remote:
remote:        Sequelize [Node: 12.16.1, CLI: 2.7.0, ORM: 3.30.4]
remote:
remote:        fs.js:35
remote:        } = primordials;
remote:            ^
remote:
remote:        ReferenceError: primordials is not defined
remote:            at fs.js:35:5
remote:            at req_ (/tmp/build_43a115e50e09530019db796929f807cd/node_modules/natives/index.js:143:24)
remote:            at Object.req [as require] (/tmp/build_43a115e50e09530019db796929f807cd/node_modules/natives/index.j
:55:10)
remote:            at Object.<anonymous> (/tmp/build_43a115e50e09530019db796929f807cd/node_modules/graceful-fs/fs.js:1:
7)
remote:            at Module._compile (internal/modules/cjs/loader.js:1158:30)
remote:            at Object.Module._extensions..js (internal/modules/cjs/loader.js:1178:10)
remote:            at Module.load (internal/modules/cjs/loader.js:1002:32)
remote:            at Function.Module._load (internal/modules/cjs/loader.js:901:14)
remote:            at Module.require (internal/modules/cjs/loader.js:1044:19)
remote:            at require (internal/modules/cjs/helpers.js:77:18)
remote:        npm ERR! code ELIFECYCLE
remote:        npm ERR! errno 1
remote:        npm ERR! androspy@1.0.0 migrate: `sequelize db:migrate`
remote:        npm ERR! Exit status 1
remote:        npm ERR!
remote:        npm ERR! Failed at the androspy@1.0.0 migrate script.
remote:        npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
remote:
remote:        npm ERR! A complete log of this run can be found in:
remote:        npm ERR!     /tmp/npmcache.9mEA8/_logs/2020-03-05T02_10_25_421Z-debug.log
remote:        ERROR: "migrate" exited with 1.
remote:        npm ERR! code ELIFECYCLE
remote:        npm ERR! errno 1
remote:        npm ERR! androspy@1.0.0 postinstall: `run-s migrate build`
remote:        npm ERR! Exit status 1
remote:        npm ERR!
remote:        npm ERR! Failed at the androspy@1.0.0 postinstall script.
remote:        npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
remote:
remote:        npm ERR! A complete log of this run can be found in:
remote:        npm ERR!     /tmp/npmcache.9mEA8/_logs/2020-03-05T02_10_25_488Z-debug.log
remote:
remote: -----> Build failed
remote:
remote:        We're sorry this build is failing! You can troubleshoot common issues here:
remote:        https://devcenter.heroku.com/articles/troubleshooting-node-deploys
remote:
remote:        Some possible problems:
remote:
remote:        - Node version not specified in package.json
remote:          https://devcenter.heroku.com/articles/nodejs-support#specifying-a-node-js-version
remote:
remote:        Love,
remote:        Heroku
remote:
remote:  !     Push rejected, failed to compile Node.js app.
remote:
remote:  !     Push failed
remote: Verifying deploy...
remote:
remote: !       Push rejected to donivarshop.
remote:
To https://git.heroku.com/donivarshop.git
 ! [remote rejected] master -> master (pre-receive hook declined)
error: failed to push some refs to 'https://git.heroku.com/donivarshop.git'
PS C:\Users\MacBook\Desktop\adobot-master>

I encountered this same problem when I used heroku and when I also tested it in localhost or cpanel, I find the same problem

**Comment by adonespitogo** [comment]
This issue can be easily fixed by updating the package.json dependencies to latest version. I'm open for pull request.

**Comment by kundanSingh11** [comment]
Just add the line 
 "engines": {
    "node": "10.18.x"
  },
after 
"main": "index.js",

**Comment by hakanonymos** [comment]
its not working , send me full version with email

**Comment by 1337C0D3RS** [comment]
follow this... this thing worked for me

https://timonweb.com/javascript/how-to-fix-referenceerror-primordials-is-not-defined-error/
